import { useState, useEffect } from "react"
import { FileText, Download, ExternalLink, RefreshCw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { getUsers } from "@/services/api"

export default function Reports() {
  const [reports, setReports] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchUsers()
  }, [])

  const fetchUsers = async () => {
    setLoading(true)
    try {
      const data = await getUsers()
      
      const allReports: any[] = [];
      data?.forEach(user => {
         if (user.assessments && user.assessments.length > 0) {
            user.assessments.forEach((assessment: any) => {
               if (assessment.pdf_url) {
                  allReports.push({
                     ...assessment,
                     user_name: user.name,
                     user_email: user.email
                  })
               }
            })
         }
      })
      
      allReports.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
      
      setReports(allReports)
    } catch (error) {
      console.error("Failed to fetch reports", error)
    } finally {
      setLoading(false)
    }
  }

  const getDownloadUrl = (url: string) => {
    if (!url) return "";
    return url.includes("?") ? `${url}&download=` : `${url}?download=`;
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Generated Reports</h2>
          <p className="text-muted-foreground">View and manage PDF reports generated by users.</p>
        </div>
        <Button variant="outline" onClick={fetchUsers} disabled={loading} className="w-full sm:w-auto">
          <RefreshCw className={`h-4 w-4 mr-2 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" /> User Assessments
          </CardTitle>
          <CardDescription>
            List of users who have completed their assessment and generated a PDF report.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="flex justify-center items-center h-48">
              <RefreshCw className="h-8 w-8 text-muted-foreground animate-spin" />
            </div>
          ) : reports.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <FileText className="h-12 w-12 mx-auto mb-4 opacity-20" />
              <p>No reports generated yet.</p>
            </div>
          ) : (
            <div className="border rounded-lg bg-card overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>User Name</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Created At</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {reports.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell className="font-medium">{report.user_name || "Unknown User"}</TableCell>
                      <TableCell>{report.user_email}</TableCell>
                      <TableCell className="text-muted-foreground">
                        {new Date(report.created_at).toLocaleString()}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          <Button variant="outline" size="sm" asChild>
                            <a href={report.pdf_url} target="_blank" rel="noreferrer">
                              <ExternalLink className="h-4 w-4 mr-2" /> View
                            </a>
                          </Button>
                          <Button variant="outline" size="sm" asChild>
                            <a href={getDownloadUrl(report.pdf_url)} download>
                              <Download className="h-4 w-4 mr-2" /> Download
                            </a>
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
