import { useState, useEffect } from "react"
import { FileText, Download, ExternalLink, RefreshCw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { getUsers } from "@/services/api"

export default function Reports() {
  const [reports, setReports] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchUsers()
  }, [])

  const fetchUsers = async () => {
    setLoading(true)
    try {
      const data = await getUsers()
      
      const allReports: any[] = [];
      data?.forEach(user => {
         if (user.assessments && user.assessments.length > 0) {
            user.assessments.forEach((assessment: any) => {
               if (assessment.pdf_url) {
                  allReports.push({
                     ...assessment,
                     user_name: user.name,
                     user_email: user.email
                  })
               }
            })
         }
      })
      
      allReports.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
      
      setReports(allReports)
    } catch (error) {
      console.error("Failed to fetch reports", error)
    } finally {
      setLoading(false)
    }
  }

  const getDownloadUrl = (url: string) => {
    if (!url) return "";
    return url.includes("?") ? `${url}&download=` : `${url}?download=`;
  }

  return (
    <div className="space-y-6 max-w-[1600px] mx-auto pb-10">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 rounded-2xl border border-slate-200/60 shadow-[0_2px_20px_rgb(0,0,0,0.02)] relative overflow-hidden">
        <div className="absolute right-0 top-0 w-64 h-64 bg-gradient-to-bl from-indigo-500/10 to-transparent rounded-full blur-3xl -z-0 pointer-events-none" />
        <div className="relative z-10">
          <h2 className="text-3xl font-black tracking-tight text-slate-900 mb-1">Generated Reports</h2>
          <p className="text-slate-500 font-medium">View and manage PDF reports generated by users.</p>
        </div>
        <Button onClick={fetchUsers} disabled={loading} className="relative z-10 bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 font-semibold shadow-sm rounded-xl px-5 h-11">
          <RefreshCw className={`h-4 w-4 mr-2 text-indigo-500 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" /> User Assessments
          </CardTitle>
          <CardDescription>
            List of users who have completed their assessment and generated a PDF report.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="flex justify-center items-center h-48">
              <RefreshCw className="h-8 w-8 text-muted-foreground animate-spin" />
            </div>
          ) : reports.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <FileText className="h-12 w-12 mx-auto mb-4 opacity-20" />
              <p>No reports generated yet.</p>
            </div>
          ) : (
            <div className="border rounded-lg bg-card overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>User Name</TableHead>
                    <TableHead>Email</TableHead>
                    <TableHead>Created At</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {reports.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell className="font-medium">{report.user_name || "Unknown User"}</TableCell>
                      <TableCell>{report.user_email}</TableCell>
                      <TableCell className="text-muted-foreground">
                        {new Date(report.created_at).toLocaleString()}
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          <Button variant="outline" size="sm" asChild>
                            <a href={report.pdf_url} target="_blank" rel="noreferrer">
                              <ExternalLink className="h-4 w-4 mr-2" /> View
                            </a>
                          </Button>
                          <Button variant="outline" size="sm" asChild>
                            <a href={getDownloadUrl(report.pdf_url)} download>
                              <Download className="h-4 w-4 mr-2" /> Download
                            </a>
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
